version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/sample-wordpress
permissions:
  - object: /var/www/html/
    owner: www-data
    group: www-data
hooks:  
  ApplicationStop:
    - location: Appstop.sh                   
  AfterInstall:
    - location: configure.sh
  ApplicationStart:
    - location: Appstart.sh
