version: 0.2
env:
 parameter-store:
    db_name: DB_NAME
    db_user: DB_USER
    db_password: DB_PASSWORD
    db_host: DB_HOST
phases:
  build:
    commands:
      - mv wp-config-sample.php wp-config.php
      - sed -i "s|database_name_here|${db_name}|g" wp-config.php
      - sed -i "s|username_here|${db_user}|g" wp-config.php
      - sed -i "s|password_here|${db_password}|g" wp-config.php
      - sed -i "s|localhost|${db_host}|g" wp-config.php
      
artifacts:
  files:
    - "**/*"
