version: 0.2
phases:
    
    build:
    commands:
      - mv wp-config-sample.php wp-config.php
      - sed -i "s|admin|$host|g" wp-config.php
      - sed -i "s|admin|$username|g" wp-config.php
      - sed -i "s|admin123|$pass|g" wp-config.php
      - sed -i "s|admin.cfdyrms3ajre.ap-south-1.rds.amazonaws.com|$endpoint|g" wp-config.php
      - sed -i "s|:3306||g" wp-config.php
      - cat wp-config.php

artifacts:
  files:
    - "**/*"
